---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /home/ubuntu/ELK-stack-multiple-node/task-1/step2/pvc-master/
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersisterntVolume
metadata:
  name: pv-quickstart-data-0
spec:
  capacity:
    storage: 1000Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/ubuntu/ELK-stack-multiple-node/task-1/step2/pvc-data/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:               
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-data-5361855-iaas.novalocal # change here
