- name: Ensure common packages are installed
  apt:
    name:
      - git
      - curl
      - vim
    state: present

- name: Ensure the latest version of Python is installed
  apt:
    name: python3
    state: latest

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present

- name: Install required Python packages
  pip:
    name:
      - ansible
      - requests
    state: latest

- name: Create a directory for application files
  file:
    path: /opt/myapp
    state: directory

- name: Copy application files
  copy:
    src: files/
    dest: /opt/myapp/
    owner: root
    group: root
    mode: '0755'