---
clusterName: "elasticsearch"
nodeGroup: "master"

# This should be set to clusterName + "-" + nodeGroup for your master group
masterService: "elasticsearch-master"

nodeSelector:
  kubernetes.io/hostname: node-master
  # Change this to the hostname of your master node

roles:
  - master

replicas: 1
minimumMasterNodes: 1

esMajorVersion: ""

esConfig:
  elasticsearch.yaml: |
    discovery.seed_hosts:
      - elasticserach-master-0
    cluster.initial_master_nodes:
      - elasticsearch-master-0

createCert: true

image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"
imagePullPolicy: IfNotPresent

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "500m"
    memory: "2Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi

service:
  type: Cluster IP