apiVersion: logstash.k8s.elastic.co/v1
kind: Logstash
metadata:
  name: quickstart
spec:
  version: 8.16.1
  count: 3
  elasticsearchRef:
    name: quickstart
    clusterName: quickstart
  config:
    log.level: info
    path.config: /usr/share/logstash/pipeline
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          generator {
            message => "Hello world!"
            count => 0
            threads => 10
          }
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
             hosts => ["https://quickstart-es-http.default.svc:9200"]
            index => "logstash-%{+YYYY.MM.dd}"
            user => "elastic"
            password => "${ES_PASSWORD}"
            ssl => true
            cacert => "/usr/share/logstash/config/certs/ca.crt"
          }
        }
  podTemplate:
    spec:
      containers:
        - name: logstash
          volumeMounts:
            - name: certs
              mountPath: /usr/share/logstash/config/certs
          env:
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-es-creds
                  key: ES_PASSWORD
      volumes:
        - name: certs
          secret:
            secretName: quickstart-es-http-certs-public
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044



# node.name: logstash-node1
# pipeline.workers: 4
# http.host: "0.0.0.0"
# xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]


# output.logstash:
#   hosts: ["logstash1:5044", "logstash2:5044", "logstash3:5044"]
#   loadbalance: true

