apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash 
metadata:
  name: ls-quickstart
  namespace: default
spec:
  version: 8.16.1
  count: 3

  # configRef:
  #   secretName: logstash-config
  # pipelinesRef:
  #   secretName: logstash-pipelines

  elasticsearchRefs:
    - name: quickstart
      namespace: default
      clusterName: es-default
    # clusterName: es-default   

  services:
    - name: beats
      service:
        spec:
          type: ClusterIP
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP

  podTemplate:
    spec:
      containers:
        - name: logstash
          env:
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-es-creds
                  key: ES_PASSWORD
          volumeMounts:
            - name: elasticsearch-certs
              mountPath: /usr/share/logstash/config/certs
              readOnly: true
            - name: pipeline-files
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: elasticsearch-certs
          secret:
            secretName: quickstart-es-http-certs-public
        - name: pipeline-files
          configMap:
            name: logstash-pipeline-files

  config:
    log.level: info
    path.config: /usr/share/logstash/pipeline
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          generator {
            message => "Hello world!"
            count => 0
            threads => 10
          }
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
             hosts => ["https://quickstart-es-http.default.svc:9200"]
            index => "logstash-%{+YYYY.MM.dd}"
            user => "elastic"
            password => "${ES_PASSWORD}"
            ssl => true
            cacert => "/usr/share/logstash/config/certs/ca.crt"
          }
        }
  






---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: quickstart-config
# stringData:
#   logstash.yml: |-
#     pipeline.workers: 4
#     log.level: debug



# node.name: logstash-node1
# pipeline.workers: 4
# http.host: "0.0.0.0"
# xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]


# output.logstash:
#   hosts: ["logstash1:5044", "logstash2:5044", "logstash3:5044"]
#   loadbalance: true

#  podTemplate:
#     spec:
#       containers:
#         - name: logstash
#           volumeMounts:
#             - name: certs
#               mountPath: /usr/share/logstash/config/certs
#           env:
#             - name: ES_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: logstash-es-creds
#                   key: ES_PASSWORD
#       volumes:
#         - name: certs
#           secret:
#             secretName: quickstart-es-http-certs-public

    # selector: {}

   # 自訂 Pod（掛 env、volume、mount）
  # podTemplate:
  #   spec:
  #     containers:
  #       - name: logstash
  #         env:
  #           - name: ES_URL
  #             valueFrom:
  #               secretKeyRef:
  #                 name: logstash-es-creds
  #                 key: ES_URL
  #           - name: ES_USERNAME
  #             valueFrom:
  #               secretKeyRef:
  #                 name: logstash-es-creds
  #                 key: ES_USERNAME
  #           - name: ES_PASSWORD
  #             valueFrom:
  #               secretKeyRef:
  #                 name: logstash-es-creds
  #                 key: ES_PASSWORD
  #         volumeMounts:
  #           - name: pipeline-files
  #             mountPath: /usr/share/logstash/pipeline
  #           - name: ca
  #             mountPath: /usr/share/logstash/config/certs
  #             readOnly: true
  
  # podTemplate:
  #   spec:
  #     containers:
  #       - name: logstash
  #         env:
  #           - name: ES_PASSWORD
  #             valueFrom:
  #               secretKeyRef:
  #                 name: logstash-es-creds
  #                 key: ES_PASSWORD
  #         volumeMounts:
  #           - name: ca
  #             mountPath: /usr/share/logstash/config/certs
  #             readOnly: true
  #           - name: pipeline-files
  #             mountPath: /usr/share/logstash/pipeline
  #     volumes:
  #       - name: ca
  #         secret:
  #           secretName: logstash-ca
  #       - name: pipeline-files
  #         configMap:
  #           name: logstash-pipeline-files

  # podTemplate:
  # spec:
  #   containers:
  #     - name: logstash
  #       volumeMounts:
  #         - name: elasticsearch-certs
  #           mountPath: /usr/share/logstash/config/certs
  #           readOnly: true
  #   volumes:
  #     - name: elasticsearch-certs
  #       secret:
  #         secretName: quickstart-es-http-certs-public