---
apiVersion: v1
data:
  ES_PASSWORD: base64密碼
kind: Secret
metadata:
  name: quickstart-ls-default-quickstart-logstash-user
  namespace: default
type: Opaque

# apiVersion: v1
# kind: Secret
# metadata:
#   name: quickstart-ls-default-quickstart-logstash-user
#   namespace: default
# type: Opaque
# stringData:
#   ES_PASSWORD: "你的明文密碼"
